#!/bin/bash

## Get Postal Version
git clone https://github.com/atech/postal src
cd src
POSTAL_VER=$(git rev-parse --short HEAD)

## Build Dockerfile
docker build --build-arg POSTAL_VER=${POSTAL_VER} -t alinuxninja/postal:latest -t alinuxninja/postal:${POSTAL_VER} .

## Docker push
docker push alinuxninja/postal
